@startuml

actor :Customer: as c
actor :Airline: as ar
actor :Administrator: as ad

rectangle "Online Travel Booking Application Use Cases" {
  left to right direction
  (Administrator logs in) as u1
  (Administrator creates Airport) as u2
  (Administrator disables Airport) as u3
  (Administrator creates Airline) as u4
  (Administrator searches for Airline) as u5
  (Administrator removes Airline) as u6
  (Airline logs in) as u12
  (Airline creates Flight) as u7
  (Airline cancels Flight) as u8
  (Airline edits Flight) as u9
  (Customer books Flight) as u10
  (Customer searches for a Flight) as u11
  (Customer looks up booking information) as u13
  (Customer logs in) as u14

  ad -- u1
  ad -- u2
  ad -- u3
  ad -- u4
  ad -- u5
  ad -- u6
  ar -- u12
  ar -- u7
  ar -- u8
  ar -- u9
  c -- u10
  c -- u11
  c -- u8
  c -- u9
  c -- u13
  c -- u14
}

@enduml