@startuml

actor :Customer: as c
actor :Airline: as ar
actor :Administrator: as ad

rectangle "Online Travel Booking Application Use Cases" {
  left to right direction
  (Login) as u1
  (Create  Airport) as u2
  (Disable Airport) as u3
  (Create Airline) as u4
  (Disable Airline) as u5
  (Create Flight) as u7
  (Manage Flight) as u8
  (View Flight Manifest) as u9
  (Book Flights) as u10
  (Search Flights) as u11
  (View Booking Information) as u12
  (Signup) as u13

  ad -- u1
  ar -- u1
  c -- u1
  ad -- u2
  ad -- u3
  ad -- u4
  ad -- u5
  ar -- u7
  ar -- u8
  ar -- u9
  c -- u10
  c -- u11
  c -- u12
  c -- u13
  u10 .> u13: include 
  u10 .> u1: include 
}

@enduml