@startuml concurreny class diagram


interface HttpRequestDispatcher {
  + dispatch(request: HttpRequest): HttpResponse
}

class HttpRequestDispatcherImpl {
  ~ {static} MAX_RETRIES: int
}

interface DataMapper<T, ID, SPEC> {
  + update(entity: T): void
}

class OptimisticLockingException {
  - message: String
}

HttpRequestDispatcherImpl .up.|> HttpRequestDispatcher
HttpRequestDispatcherImpl .down.> OptimisticLockingException: catches
DataMapper .down.> OptimisticLockingException: throws

@enduml