@startuml front controller

participant "DispatcherServlet" as diss
participant "httpRequest:HttpRequest" as req
participant "HttpRequestDispatcher" as dispatcher
participant "WebApplicationContext" as webCtx
participant "delegate:HttpRequestDelegate" as delegate
participant "httpResponse:HttpResponse" as res
participant "IdentityMapper" as imap
participant "UnitOfWork" as uow
participant "restResponse:RestResponse" as restres
participant "objectMapper:ObjectMapper" as objmap

[-> diss: service(request, response)
activate diss
note over req: constructor simplified here for brevity
diss -> req **: new HttpRequest(request)
diss -> dispatcher: dispatch(request)
activate dispatcher
dispatcher -> dispatcher: doDispatch(request)
activate dispatcher
dispatcher -> req: path =  getPath()
activate req
deactivate req
dispatcher -> webCtx: delegates = getDelgatesForPath(request.getPath())
activate webCtx
deactivate webCtx
alt delagates is empty
  note over res: constructor call simplified for brevity
  dispatcher -> res **: new HttpResponse(NotFound, errorBody, headers)
  dispatcher --> diss: httpResponse
else
  alt is prefight request
    dispatcher -> res **: new HttpResponse(NoContent, null, preflightHeaders)
    dispatcher --> diss: httpResponse
  else
    loop for delegate in delegates
      dispatcher -> delegate: methods = getMethods()
      activate delegate
      deactivate delegate
      dispatcher -> req: method = getMethod()
      activate req
      deactivate req
      opt methods contains method
        dispatcher -> dispatcher: handle(httpRequest)
        activate dispatcher
        dispatcher -> imap: reset()
        activate imap
        deactivate imap
        dispatcher -> uow: start()
        activate uow
        deactivate uow
        dispatcher -> delegate: handle(request)
        activate delegate
        delegate -> restres **: new RestResponse(status, body, headers)
        ref over delegate: see delegate flow
        alt
          delegate --> dispatcher: restResponse
          dispatcher -> restres: body = getBody()
          activate restres
          deactivate restres
          opt body exists
            dispatcher -> webCtx: objectMapper = getObjectMapper()
            activate webCtx
            deactivate webCtx
            dispatcher -> objmap: bodyStr = writeValueAsString(body)
            activate objmap
            deactivate objmap
          end
          dispatcher -> restres: status = getStatus()
          activate restres
          deactivate restres
          dispatcher -> uow: commit()
          activate uow
          deactivate uow
          dispatcher -> res **: new HttpResponse(status, bodyStr, headers)
          dispatcher --> diss: httpResponse
        else exception thrown from delegate
          dispatcher -> uow: rollback()
          activate uow
          deactivate uow
          dispatcher -> res **: new HttpResponse(InternalServerError, errorBody, headers)
          dispatcher --> diss: httpResponse
          deactivate delegate
        end
      end
      dispatcher -> res **: new HttpResponse(MethodNotAllowed, errorBody, headers)
      dispatcher --> diss: httpResponse
      deactivate dispatcher
      deactivate dispatcher
      deactivate dispatcher
    end
  end
end
diss -> res: send(response)
@enduml