name: Deploy Frontend

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ env.APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          healthcheck: https://${{ env.APP_NAME }}.herokuapp.com
          usedocker: true
          appdir: 'frontend'
          branch: ${GITHUB_REF}
          delay: 30
        env:
          APP_NAME: frontend-2-pizzas
