name: Deploy Frontend

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0 # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your heroku api key
          app_name: https://${{ env.APP_NAME }}.herokuapp.com
          dockerfile_path: 'frontend'
          branch: ${GITHUB_REF}
          delay: 30
        env:
          APP_NAME: frontend-2-pizzas
