name: Lint Frontend

on:
  workflow_dispatch:
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build Docker image
        working-directory: ./frontend
        run: docker build . -f ./Dockerfile.dev -t 2-pizzas-frontend:$GITHUB_RUN_ID
      - name: Lint
        working-directory: ./frontend
        run: docker run 2-pizzas-frontend:$GITHUB_RUN_ID yarn lint
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.14.1'
      - run: npm install -g yarn && yarn init -y && yarn
      - uses: cypress-io/github-action@v2
        with:
          start: 'cd frontend && yarn start'
          wait-on: 'http://localhost:3000'
          browser: chrome
          project: ./frontend
          headless: true
