name: Lint and Test Frontend

on:
  workflow_dispatch:
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build Docker image
        working-directory: ./frontend
        run: docker build . -f ./Dockerfile.dev -t 2-pizzas-frontend:$GITHUB_RUN_ID
      - name: Lint
        working-directory: ./frontend
        run: docker run 2-pizzas-frontend:$GITHUB_RUN_ID yarn lint
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/included:3.8.3
    steps:
      - uses: actions/checkout@v2
      - run: cypress run --project ./frontend
