name: Lint and Test Frontend

on:
  workflow_dispatch:
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build Docker image
        working-directory: ./frontend
        run: docker build . -f ./Dockerfile.dev -t 2-pizzas-frontend:$GITHUB_RUN_ID
      - name: Lint
        working-directory: ./frontend
        run: docker run 2-pizzas-frontend:$GITHUB_RUN_ID yarn lint
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          project: ./frontend
          headless: true
