name: Reset Database

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.6-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - {{ secrets.DB_PORT }}:{{ secrets.DB_PORT }}
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Reset database
        working-directory: ./backend
        run: psql postgres://{{ secrets.DB_USER }}:{{ secrets.DB_PASSWORD }}@{{ secrets.DB_HOST }}:{{ secrets.DB_PORT }}/{{ secrets.DB_NAME }} -f ./init.sql
