name: Test Backend

on:
  workflow_dispatch:
  pull_request:
    branches: [ main, develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run tests
      working-directory: ./backend
      run: mvn test
    