name: Test Backend

on:
  workflow_dispatch:
  pull_request:
    branches: [ main, develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run tests
      working-directory: ./backend
      run: mvn -Dprofile=test -Denv.DATABASE_USERNAME=${{ secrets.DB_USER }} -Denv.DATABASE_PASSWORD=${{ secrets.DB_PASSWORD }} clean test 
    env:
      DATABASE_USERNAME: ${{ secrets.DB_USER }}
      DATABASE_PASSWORD: ${{ secrets.DB_PASSWORD }}
         